### ISSUE TITLE
Where is the ConstantUtils in old GTIS?

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#95]
Where is the class that has the same functionality as this class: https://github.com/opprop/generic-type-inference-solver/blob/master/src/util/ConstantUtils.java ？

**Comment by CharlesZ-Chen** [comment]
This class has been deleted as we discussed on the group meeting.

**Comment by topnessman** [comment]
What was the reason it is deleted? I found it useful to determine a constraint between two ConstantSlots holds or not.

**Comment by CharlesZ-Chen** [comment]
The reason is currently nobody using it. And the implementation is somehow ugly, see my code comment in that class:

https://github.com/opprop/checker-framework-inference/pull/89/commits/62e324238817b7a6beba42f1d55a1c9f43a0208f

**Comment by topnessman** [comment]
I agree with your comment. I will refactor the implementation, but I think we need to keep the functionality because of the use case I mentioned.

**Comment by CharlesZ-Chen** [comment]
What is your use case? I.e. where would you like to determine if a constraint between two constant slots holds?

**Comment by topnessman** [comment]
See this line: https://github.com/opprop/checker-framework-inference/pull/96/files#diff-ebc4ea4d861d396f522dfb8cad6a140dR51
It was called early verification before.

**Comment by CharlesZ-Chen** [comment]
I see. I remembered that we've discussed the early verification in the group meeting, and the conclusion was:

We do early verification in `ConstraintManager`, and abort early with an `Unsatisfiable` information/exception. Then in the Serializing phase, we just focus on serializing constraints.

Currently, the only case I can imagine that Serializer will serialize a contradict constraint should be `ConstraintManager` failed detecting this contradict constraint, which means we have mal-implementation of early verification in `ConstraintManager`.

If we want to have a double check in Serializing phase, maybe we abort early with `Unsatisfiable` instead of passing serialized constraints into solver and let solver trying to solve it even though we've already know solver will fail to found a solution?

**Comment by topnessman** [comment]
> maybe we abort early with Unsatisfiable instead of passing serialized constraints into solver
1. Do we need to abort instantly once we find a contradicting constraint over two constants?
Right now we can do that.  As that constraint is a must-satisfiable constraint, and if that can't be satisfied, aborting early makes sense. But in the future, if we add IfConstraint(or ImpliesConstraint saying if my condition holds, then conclusion constraint should also hold), if the IfConstraint is between two constants that is guaranteed to not satisfy, we don't abort, because condition can be satisfiable or not-satisfiable and it doesn't influence the whole inference solving process.

>  and let solver trying to solve it even though we've already know solver will fail to found a solution

2. As fart as I know, Sat4j solver can detect contradicting constraint before it starts actual solving process. I'm not sure if the other backends(Logiql & Z3) have such intelligent mechanism or not.

**Comment by CharlesZ-Chen** [comment]
Regarding the `ImpliesConstraint`:

If the conclusion is a constant constraint, I suggest we do simplification in `ConstraintManager`, and leave `Searilizer` just focus on serializing constraints without checking. Reasons:

In the case of conclusion of a satisfiable constant constraint, actually we can safely ignore this whole impliedConstraint. I.e. `ConstraintManager` can safely filter out this constraint. (here is the case equal to substituting it with an empty value during serializing phase, even better, serializer doesn't need to serialize this constraint at all).

In the case of conclusion of an unsatisfiable constant constraint, it is better to keep the original constant constraint passed into solver, instead of substituting it with an arbitrary contradictory value  set by `VariableCombos` (As we want to keep the reasoning).

So in this case, Serializer still just serializing this contradictory constraint without checking.

**Comment by CharlesZ-Chen** [comment]
Overall, in my opinion, the architecture of early verification would be:

In `ConstriantManager` :

1. Check constant constraints: if there were unsatisfiable constant constraints that is not representing any conclusions of implied constraints, early abort.

2. Simplify impliesConstraints: 
 - If conclusion is satisfiable constant constraint, ignore this implied constraint.
 - If conclusion is unsatisfiable constant constraint, keep this implied constraint.

In `FormatTranslator`:

Just serializing constraints, without any constant verification.

**Comment by topnessman** [comment]
Thanks for pointing it out. Sorry I'm not sure I understand your above comment, so let's discuss in person.
We can discuss the problem in two scenarios:
If ImpliesConstraint doesn't come into the picture:
If ConstraintManager sees any not-satisfaiable two-constants constraint, it instantly exits the inference process - meaning no furthur constraints can be added, no solvers will be involed. The inference just exists with an "Inferene failed" error message.

If we consider ImpliesConstraint(format: assumption1 && assumption 2 && ... -> conclusion0):
If  any not-satisfaiable two-constants constraint appears in assumption(meaning assumption is false, then the conclusion can be any result), constraint manager don't add the ImpliesConstraint and report in the result that this ImpliesConstraint is ignored because of the assumption doesn't hold. But if a satisfaiable two-constants constraint appears in assumption, it's equivalent to saying "true & (other constraints)", so we don't need to consider that two-constants constraint.
But if  any not-satisfaiable two-constants constraint appears in conclusion, it's slightly tricky. For example, if we have such ImpliesConstraint:
(@1 <: @2) & (@3 = @Rep) => @Rep = @Any
Then how do we encode this ImpliesConstraint?

**Comment by topnessman** [comment]
Resolve by adding ConstraintVerifier
